export const sample_foods = [
    {
      id: '1',
      name: 'Pizza ',
      cookTime: '10-20',
      price: 200,
      favorite: false,
      origins: ['Not from India'],
      stars: 4.5,
      imageUrl: 'food-1.jpg',
      tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
      id: '2',
      name: 'Burger',
      cookTime: '15-25',
      price: 100,
      favorite: true,
      origins: ['Not from India'],
      stars: 4.7,
      imageUrl: 'food-2.jpg',
      tags: ['FastFood', 'Bread'],
    },
    {
      id: '3',
      name: 'Noodles',
      cookTime: '50-60',
      price: 120,
      favorite: false,
      origins: ['China'],
      stars: 4.3,
      imageUrl: 'food-3.jpg',
      tags: ['Chinese', 'Lunch', 'Spicy'],
    },
    {
      id: '4',
      name: 'Pav bhaji',
      cookTime: '5-15',
      price: 9,
      favorite: true,
      origins: ['Mumabai'],
      stars: 4.6,
      imageUrl: 'food-4.jpg',
      tags: ['FastFood', 'Indian'],
    },
    {
      id: '5',
      name: 'Tea',
      cookTime: '30-40',
      price: 20,
      favorite: false,
      origins: ['India/Asia'],
      stars: 4.9,
      imageUrl: 'food-5.jpg',
      tags: ['Seafood', 'Indian'],
    },
    {
      id: '6',
      name: 'Roti',
      cookTime: '20-30',
      price: 10,
      favorite: true,
      origins: ['India'],
      stars: 4.4,
      imageUrl: 'food-6.jpg',
      tags: ['Lunch', 'Indian'],
    },
  ];
  

  export const sample_tags=[
    {name:'All', count:6},
    {name:'Indian', count:3},
    {name:'FastFood', count:3},
    {name:'Lunch', count:3},
    {name:'Pizza', count:1},
    {name:'Chinese', count:1},
  ];