export const sample_foods = [
    {
      id: '1',
      name: 'Pizza Pepperoni',
      cookTime: '10-20',
      price: 10,
      favorite: false,
      origins: ['Italy'],
      stars: 4.5,
      imageUrl: 'food-1.jpg',
      tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
      id: '2',
      name: 'Meatball',
      cookTime: '15-25',
      price: 12,
      favorite: true,
      origins: ['USA'],
      stars: 4.7,
      imageUrl: 'food-2.jpg',
      tags: ['FastFood', 'Meat'],
    },
    {
      id: '3',
      name: 'Chicken Biryani',
      cookTime: '50-60',
      price: 8,
      favorite: false,
      origins: ['India'],
      stars: 4.3,
      imageUrl: 'food-3.jpg',
      tags: ['Rice', 'Lunch', 'Spicy'],
    },
    {
      id: '4',
      name: 'Cheeseburger',
      cookTime: '5-15',
      price: 9,
      favorite: true,
      origins: ['USA'],
      stars: 4.6,
      imageUrl: 'food-4.jpg',
      tags: ['FastFood', 'Burger'],
    },
    {
      id: '5',
      name: 'Sushi',
      cookTime: '30-40',
      price: 20,
      favorite: false,
      origins: ['Japan'],
      stars: 4.9,
      imageUrl: 'food-5.jpg',
      tags: ['Seafood', 'Lunch'],
    },
    {
      id: '6',
      name: 'Pasta Carbonara',
      cookTime: '20-30',
      price: 15,
      favorite: true,
      origins: ['Italy'],
      stars: 4.4,
      imageUrl: 'food-6.jpg',
      tags: ['Pasta', 'Dinner'],
    },
  ];
  

  export const sample_tags=[
    {name:'All', count:6},
    {name:'Snacks', count:4},
    {name:'FastFood', count:5},
    {name:'Lunch', count:2},
    {name:'Pizza', count:1},
    {name:'Non-FastFood', count:2},
  ];